[package]
name = "temperature_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.19.0"
url = "2.3.1"
noise = "0.8.2"
rand = "0.8.5"
